title: <p align="center"> Aishwarya Das </p>
logo: /assets/img/logo2.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/aishwarya-das/">LinkedIn</a> |
  <a href="https://github.com/aishwarya129">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning & NLP related problems.
  Working with Boeing India since 2018 .
  <br>
  </p>



theme: jekyll-theme-minimal
